# Generated by Django 3.0.2 on 2020-02-15 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rodamiento',
            fields=[
                ('PK_ROD', models.AutoField(primary_key=True, serialize=False)),
                ('D_INT_A', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('D_INT_A1', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('D_EXT_D', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('D_EXT_D1', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('D_ESP_B', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('D_ESP_C', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('D_ESP_T', models.DecimalField(decimal_places=5, max_digits=15, null=True)),
                ('N_PARTE_1', models.CharField(max_length=100, null=True)),
                ('N_PARTE_2', models.CharField(max_length=100, null=True)),
                ('DESCRIPCION', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Rodamiento',
            fields=[
                ('PK_TIPO_ROD', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('TIPO', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equivalente',
            fields=[
                ('FK_RODAMIENTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mantenedor.Rodamiento')),
                ('N_ROD', models.CharField(max_length=100, null=True)),
                ('MARCA', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rodamiento',
            name='FK_TIPO_ROD',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.ProtectedError, to='mantenedor.Tipo_Rodamiento'),
        ),
    ]
